POST http://localhost:5000/api/persons
content-type: application/json

{
    "name": "Alema Edrick",
    "number": "7765452425"
}

###

GET http://localhost:5000/api/persons

###
GET http://localhost:5000/api/persons/655b25086eee68e551842615

###
DELETE http://localhost:5000/api/persons/655b25086eee68e551842615