POST http://localhost:5000/api/persons
content-type: application/json

{
    "name": "Eddy",
    "number": "536353663"
}

###

GET http://localhost:5000/api/persons

###
GET http://localhost:5000/api/persons/1

###
DELETE http://localhost:5000/api/persons/1